/**
 * PDF Export Lock Module
 * 
 * A module to prevent duplicate PDF generation when sections are expanded
 * Uses timestamps to track when PDFs were generated and ensure only one generation
 * completes per user action.
 */

// Track the timestamp of when PDF was last generated
let lastGeneratedTimestamp: number | null = null;

// Default cooldown period in milliseconds (500ms is usually sufficient)
const GENERATION_COOLDOWN = 500;

/**
 * Check if a PDF was recently generated based on timestamp
 * @returns boolean indicating if PDF was generated within cooldown period
 */
export function wasGenerated(): boolean {
  if (!lastGeneratedTimestamp) {
    return false;
  }
  
  const now = Date.now();
  const timeSinceGeneration = now - lastGeneratedTimestamp;
  
  // Consider generation still active if within cooldown period
  return timeSinceGeneration < GENERATION_COOLDOWN;
}

/**
 * Mark that a PDF was generated by storing the current timestamp
 */
export function markAsGenerated(): void {
  lastGeneratedTimestamp = Date.now();
  console.log("PDF generation marked at timestamp:", lastGeneratedTimestamp);
}

/**
 * Reset the generation state (can be used when changing pages or explicitly canceling)
 */
export function reset(): void {
  lastGeneratedTimestamp = null;
  console.log("PDF generation lock reset");
}

export default {
  wasGenerated,
  markAsGenerated,
  reset
};