/**
 * This utility module provides thread-safe PDF export locking mechanisms
 * to prevent duplicate PDF generations when a user clicks the export button multiple times
 */

// Private state variables
let isGeneratingPdf = false;
let lastGeneratedTimestamp: number | null = null;
const COOLDOWN_PERIOD = 3000; // 3 seconds cooldown between PDF generations

/**
 * Check if a PDF was recently generated based on timestamp
 * @returns boolean indicating if PDF was generated within cooldown period
 */
export function wasGenerated(): boolean {
  if (!lastGeneratedTimestamp) return false;
  
  const now = Date.now();
  return (now - lastGeneratedTimestamp) < COOLDOWN_PERIOD;
}

/**
 * Mark that a PDF was generated by storing the current timestamp
 */
export function markAsGenerated(): void {
  lastGeneratedTimestamp = Date.now();
}

/**
 * Check if PDF generation is currently in progress
 * @returns boolean indicating if generation is in progress
 */
export function isGenerating(): boolean {
  return isGeneratingPdf;
}

/**
 * Start PDF generation process
 */
export function startGeneration(): void {
  isGeneratingPdf = true;
}

/**
 * Reset the generation state (can be used when changing pages or explicitly canceling)
 */
export function reset(): void {
  isGeneratingPdf = false;
}

export default {
  wasGenerated,
  markAsGenerated,
  isGenerating,
  startGeneration,
  reset
};